WebApp1/Pages/AddRooms.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp1.Data;
using System;
using System.Linq;

namespace WebApp1.Pages
{
    [Authorize]
    public class AddRoomsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public AddRoomsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Room? Room { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
            
                _context.Rooms.Add(Room);
                await _context.SaveChangesAsync();
                Console.WriteLine(Room.Id + " " + Room.RoomName + " " + Room.Capacity + " has been added successfully!");
                return RedirectToPage("./ListRooms", new { success = true });
            }
            else
            {
                Console.WriteLine("Room can not add to DB!");
                return RedirectToPage("./Index", new { success = false });
            }
        }

    }
}

WebApp1/Pages/CreateReservation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using WebApp1.Data;

namespace WebApp1.Pages
{
    [Authorize]
    public class CreateReservationModel : PageModel
    {

        private readonly ApplicationDbContext _context;
        public IList<Room> Rooms { get; set; }
        public Room? Room { get; set; } = new Room();

         [BindProperty]
        public Reservation Reservation { get; set; } = new Reservation();

        public CreateReservationModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task OnGetAsync()
        {
            Rooms = await _context.Rooms.ToListAsync();
        }


        public async Task<IActionResult> OnPostAsync(int roomId)
        {

            if (ModelState.IsValid)
            {
                var room = await _context.Rooms.FindAsync(roomId);
                if (room == null)
                {
                    return NotFound();
                }

                Reservation.Room = room;

                _context.Reservations.Add(Reservation);
                await _context.SaveChangesAsync();
                Console.WriteLine(Reservation.Id + "id number, " + Reservation.ReserverName + "for this name, " + Reservation.Room + " for this room, has been added successfully!");
                return RedirectToPage("./ReservationTable");
            }
            else
            {
                Console.WriteLine("Reservation can not created!");
                return RedirectToPage("./HomePage");
            }
        }
    }
}

WebApp1/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

WebApp1/Pages/HomePage.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp1.Data;
namespace WebApp1.Pages
{

[Authorize]

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}
}

WebApp1/Pages/ListRooms.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApp1.Data;

namespace WebApp1.Pages
{
    [Authorize]
    public class ListRoomsModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public IList<Room>? IRooms { get; set; }
        public Room? Room { get; set; } = new Room();

        public ListRoomsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task OnGet()
        {
            IRooms = await _context.Rooms.ToListAsync() ?? new List<Room>();
        }

        public async Task<IActionResult> OnPostRemove(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }

            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEditRoomAsync(int roomId, string roomName, int capacity)
        {
            var room = await _context.Rooms.FindAsync(roomId);
            if (room == null)
            {
                return NotFound();
            }

            room.RoomName = roomName;
            room.Capacity = capacity;
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }

    }
}

WebApp1/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp1.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

WebApp1/Pages/ReservationTable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using WebApp1.Data;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace WebApp1.Pages
{
    [Authorize]
    public class ReservationTableModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IList<Reservation> IReservations { get; set; }
        public List<string> DaysOfWeek { get; set; }
        public List<string> HoursOfDay { get; set; }

        [BindProperty(SupportsGet = true)]
        public string RoomName { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Capacity { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public DateTime StartDate { get; set; } = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek);

        [BindProperty(SupportsGet = true)]
        public DateTime EndDate { get; set; } = DateTime.Today.AddDays(6 - (int)DateTime.Today.DayOfWeek);

        public ReservationTableModel(ApplicationDbContext context)
        {
            _context = context;
            DaysOfWeek = new List<string> { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" };
            HoursOfDay = Enumerable.Range(0, 24).Select(i => $"{i:00}:00").ToList();
        }

        public async Task OnGetAsync()
        {
            var query = _context.Reservations
                                .Include(r => r.Room)
                                .AsQueryable();

            if (!string.IsNullOrEmpty(RoomName))
            {
                query = query.Where(r => r.Room.RoomName.Contains(RoomName));
            }

            if (Capacity > 0)
            {
                query = query.Where(r => r.Room.Capacity == Capacity);
            }

            if (StartDate != DateTime.MinValue && EndDate != DateTime.MinValue)
            {
                query = query.Where(r => r.Date >= StartDate && r.Date <= EndDate);
            }

            IReservations = await query.ToListAsync();
        }

        public async Task<IActionResult> OnPostRemoveAsync(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }

            _context.Reservations.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEditAsync(int id, string roomName, DateTime date, DateTime time)
        {
            var reservation = await _context.Reservations
                                            .Include(r => r.Room)
                                            .FirstOrDefaultAsync(r => r.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            if (reservation.Room == null)
            {
                reservation.Room = new Room();
            }

            reservation.Room.RoomName = roomName;
            reservation.Date = date;
            reservation.Time = time;
            await _context.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

WebApp1/Pages/AddRooms.cshtml
@page
@model WebApp1.Pages.AddRoomsModel


<head>
    <title>Login 10</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body class="img js-fullheight"
    style="background-image: url(https://bilimgenc.tubitak.gov.tr/sites/default/files/etkileyici_doga_fotograflari_4.jpg); background-size: cover; background-repeat: no-repeat;background-attachment: fixed;">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h1 class="heading-section" style="color:white">Lab 10</h1>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center" style="color:white">Do you Want Add Room</h3>
                        <form class="requires-validation" method="post" novalidate>

                            <div class="col-md-12">
                                <input class="form-control" type="text-black" style="opacity:0.6;border-radius:15px; height:50px" name="Room.RoomName"
                                    placeholder="Room Name" required> <br>
                                <div class="valid-feedback">Room Name field is valid!</div>
                                <div class="invalid-feedback">Room Name field cannot be blank!</div>
                            </div>

                            <div class="col-md-12">
                                <input class="form-control" type="number" style="opacity:0.6;border-radius:15px; height:50px" name="Room.Capacity" placeholder="Capacity"
                                    required> <br>
                                <div class="valid-feedback">Capacity field is valid!</div>
                                <div class="invalid-feedback">Capacity field cannot be blank!</div>
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                                <label class="form-check-label">Datas Correct</label>
                                <div class="invalid-feedback">Please confirm that the entered data are all correct!
                                </div>
                            </div>


                            <div class="form-button mt-3">
                                <button id="submit" type="submit" class="btn btn-primary" onclick="OnPostAsync" style="background-color:green; color:black"> Add</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script>
    <script defer
        src="https://static.cloudflareinsights.com/beacon.min.js/vedd3670a3b1c4e178fdfb0cc912d969e1713874337387"
        integrity="sha512-EzCudv2gYygrCcVhu65FkAxclf3mYM6BCwiGUm6BEuLzSb5ulVhgokzCZED7yMIkzYVg65mxfIBNdNra5ZFNyQ=="
        data-cf-beacon='{"rayId":"883352afb86170ce","version":"2024.4.1","token":"cd0b4b3a733644fc843ef0b185f98241"}'
        crossorigin="anonymous"></script>
</body>

WebApp1/Pages/CreateReservation.cshtml
@page
@model WebApp1.Pages.CreateReservationModel
@{
    ViewData["Title"] = "Create Reservation";
}



<link rel="stylesheet" href="../css/createReservationForm.css">


<div class="form-body" >
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Create Reservation</h3>
                    <p>(Reserver name and ID set automatically)</p>
                    <form class="requires-validation" method="post" novalidate>

                        <div class="col-md-12">
                            <label for="reserverName">Reserver Name</label>
                            <input class="form-control" type="text-black" name="Reservation.ReserverName"
                                value="@User.Identity.Name" readonly required>
                        </div>
                        <br />

                        <div class="col-md-12">
                            <label for="reservationDate">Reservation Date</label>
                            <input type="date" id="reservationDate" name="Reservation.Date" class="form-control" />
                            <div class="valid-feedback">Date field is valid!</div>
                            <div class="invalid-feedback">Date field cannot be blank!</div>
                        </div>
                        <br />

                        <div class="col-md-12">
                            <label for="reservationTime">Reservation Time</label>
                            <input type="time" id="reservationTime" asp-for="Reservation.Time" class="form-control" />
                            <div class="valid-feedback">Time field is valid!</div>
                            <div class="invalid-feedback">Time field cannot be blank!</div>
                        </div>
                        <br />

                        <div class="col-md-12">
                            <label for="roomListDropdown">Room List</label>
                            <select class="form-select mt-1" id="roomListDropdown" name="roomId" required>
                                <option selected disabled>Rooms</option>
                                @foreach (var room in Model.Rooms)
                                {
                                    <option value="@room.Id">@room.RoomName</option>
                                }
                            </select>
                            <div class="valid-feedback">You selected a room!</div>
                            <div class="invalid-feedback">Please select a room from list!</div>
                        </div>
                        <br />

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">Make Reservation</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="~/js/createReservationForm.js"></script>

WebApp1/Pages/HomePage.cshtml
@page
@model WebApp1.Pages.IndexModel

@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp1/Pages/ListRooms.cshtml
@page
@model WebApp1.Pages.ListRoomsModel


@{
    ViewData["Title"] = "ListRooms";
}

<link rel="stylesheet" href="../css/ListRoom.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div class="panel">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-sm-12 col-xs-12"
                style="display: flex; justify-content: space-between; align-items: center;">
                <h4 class="title">Data List</h4>
                <a asp-page="/AddRooms" data-tip="add" style="color:white"><i class="fa fa-add"
                        style="color:white"></i>Add New Room</a>
            </div>
        </div>
        <div class="panel-body table-responsive">
           

            @if (Model.IRooms != null && Model.IRooms.Any())
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Room Name</th>
                            <th>Capacity</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var room in Model.IRooms)
                        {
                            <tr>
                                <td>@room.Id</td>
                                <td>@room.RoomName</td>
                                <td>@room.Capacity</td>
                                <td>
                                    <form method="post" asp-page-handler="EditRoom" asp-route-roomId="@room.Id"
                                        style="display:inline">
                                        <button type="button" onclick="showInputForm('@room.Id')" class="btn btn-danger"><i
                                                class="fa fa-edit"></i></button>
                                        <input id="eRoomName-@room.Id" style="display:none" type="text" name="roomName"
                                            value="@room.RoomName" />
                                        <input id="eRoomCapacity-@room.Id" style="display:none" type="number" name="capacity"
                                            value="@room.Capacity" />
                                        <button id="eOkeyButton-@room.Id" style="display:none" type="submit"
                                            class="btn btn-danger"><i class="fa fa-check-circle"></i></button>
                                    </form>

                                    <form method="post" asp-page-handler="Remove" asp-route-id="@room.Id" style="display:inline"
                                        onsubmit="return confirm('Are you sure you want to delete this?');">
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p style="color:white">No rooms available! Start by adding a room.</p>
            }
        </div>
    </div>
</div>


<script src="~/js/ListRoom.js"></script>

WebApp1/Pages/ReservationTable.cshtml
@page
@model WebApp1.Pages.ReservationTableModel
@{
    ViewData["Title"] = "Reservation Table";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link rel="stylesheet" href="../css/reservationTable.css">

<div class="panel">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-sm-12 col-xs-12" style="display: flex; justify-content: space-between; align-items: center;">
                <h4 class="title">Reservation Table</h4>
                <a asp-page="/CreateReservation" data-tip="add" class="btn btn-primary"><i class="fa fa-add"></i> Create New Reservation</a>
            </div>
        </div>
    </div>

    <div class="panel-body table-responsive">
        <!-- Filtreleme Formu -->
        <form method="get" asp-page-handler="Filtered" class="form-inline d-flex justify-content-start" style="margin-bottom: 10px;">
            <div class="form-group mx-sm-2">
                <label for="roomName" style="color:white; margin-right: 5px;">Room Name:</label>
                <input type="text" class="form-control" id="roomName" name="roomName" placeholder="Enter room name" value="@Model.RoomName" />
            </div>
            <div class="form-group mx-sm-2">
                <label for="capacity" style="color:white; margin-right: 5px;">Capacity:</label>
                <input type="number" class="form-control" id="capacity" name="capacity" placeholder="Enter capacity" value="@Model.Capacity" />
            </div>
            <div class="form-group mx-sm-2">
                <label for="startDate" style="color:white; margin-right: 5px;">Start Date:</label>
                <input type="date" class="form-control" id="startDate" name="startDate" placeholder="Filtered by start date" value="@Model.StartDate.ToString("yyyy-MM-dd")" />
            </div>
            <div class="form-group mx-sm-2">
                <label for="endDate" style="color:white; margin-right: 5px;">End Date:</label>
                <input type="date" class="form-control" id="endDate" name="endDate" placeholder="Filtered by end date" value="@Model.EndDate.ToString("yyyy-MM-dd")" />
            </div>
            <button type="submit" class="btn btn-primary mx-sm-2" style="margin-top: 22px; height: 40px; width: 100px;">Filter</button>
        </form>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Time</th>
                    @foreach (var day in Model.DaysOfWeek)
                    {
                        <th>@day</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var hour in Model.HoursOfDay)
                {
                    <tr>
                        <td>@hour</td>
                        @foreach (var day in Model.DaysOfWeek)
                        {
                            <td>
                                @{
                                    var reservations = Model.IReservations.Where(r => r.Date.DayOfWeek.ToString() == day && r.Time.ToString("HH:mm") == hour).ToList();
                                }
                                @if (reservations.Any())
                                {
                                    foreach (var reservation in reservations)
                                    {
                                        <div class="reservation-item">
                                            @reservation.ReserverName
                                            <form method="post" asp-page-handler="Edit" asp-route-id="@reservation.Id" style="display:inline">
                                                <button type="button" onclick="showInputForm('@reservation.Id')" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></button>
                                                <input id="eRoomName-@reservation.Id" style="display:none" type="text" name="roomName" value="@reservation.Room.RoomName" />
                                                <input id="eDate-@reservation.Id" style="display:none" type="date" name="date" value="@reservation.Date.ToString("yyyy-MM-dd")" />
                                                <input id="eTime-@reservation.Id" style="display:none" type="time" name="time" value="@reservation.Time.ToString(@"hh\:mm\:ss")" />
                                                <button id="eOkeyButton-@reservation.Id" style="display:none" type="submit" class="btn btn-sm btn-success"><i class="fa fa-check-circle"></i></button>
                                            </form>
                                            <form method="post" asp-page-handler="Remove" asp-route-id="@reservation.Id" style="display:inline" onsubmit="return confirm('Are you sure you want to delete this?');">
                                                <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </div>
                                    }
                                }
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
function showInputForm(id) {
    document.getElementById('eRoomName-' + id).style.display = 'inline';
    document.getElementById('eDate-' + id).style.display = 'inline';
    document.getElementById('eTime-' + id).style.display = 'inline';
    document.getElementById('eOkeyButton-' + id).style.display = 'inline';
}
</script>